export const ActionTypes = {
  ADD_CITY: "ADD_CITY",
  DELETE_CITY: "DELETE_CITY",
  POST_LOADING: "POST_LOADING",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  REMOVE_CITYS: "REMOVE_CITYS",
  REFRESH_CITYS: "REFRESH_CITYS",
};
